### PR TITLE
[dev] Build Bonita 7.11.0 developments

### PR DESCRIPTION
**Pull request by tbouffard**

### CODE REVIEW

**Comment by tbouffard** [comment]
7.10.0.W9 build failure due to https://github.com/bonitasoft/bonita-engine/commit/78236a4813f76efee1f8a31aaa75438126d08be2
The related bonita-engine [Travis CI build](https://travis-ci.org/bonitasoft/bonita-engine/builds/651325282) fails with the same error as 09efffa

```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/travis/build/bonitasoft/bonita-engine/bonita-integration-tests/bonita-integration-tests-client/build.gradle' line: 3
* What went wrong:
Plugin [id: 'bonita-license-extractor'] was not found in any of the following sources:
- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/5.3/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)
```

**Comment by tbouffard** [comment]
7.11.0.W10 error:
- engine fixed
- studio now failed: https://github.com/Bonitasoft-Community/Build-Bonita/pull/48/checks?check_run_id=464782380
```
[DEBUG] Running build command: ./mvnw --quiet clean verify -DskipTests -Pdefault,all-in-one,!jdk11-tests -Dengine.version=7.11.0.W10 -Dfilters.version=7.11.0.W10
[ERROR] Failed to resolve target definition /Users/runner/runners/2.165.2/work/Build-Bonita/Build-Bonita/bonita-studio/platform/platform.target: Failed to load p2 metadata repository from location http://repositories.rd.lan/p2/4.14/: Unknown Host: http://repositories.rd.lan/p2/4.14/content.xml: Unknown host repositories.rd.lan -> [Help 1]
```

**Comment by tbouffard** [comment]
7.11.0.W12 error: bonita-userfilters
Missing engine pom
```
Non-resolvable import POM: Could not find artifact org.bonitasoft.engine:bonita-engine:pom:7.11.0.W12
```

**Comment by tbouffard** [comment]
:heavy_check_mark: 7.11.0.W13 pass
- userfilters missing pom fixed
- studio p2 repository: https://github.com/bonitasoft/bonita-studio/commit/a3b21ea422c7c876647bc13a80fa2c83045854cb

**Comment by baptistemesta** [comment]
As far as I know, nothing was done to fix userfilter missing pom.
Do you know more on that point?

**Comment by tbouffard** [comment]
> As far as I know, nothing was done to fix userfilter missing pom.
> Do you know more on that point?

Not at all
I had a quick look at the `bonita-engine` git commit changelog  from `7.11.0.W12` to `7.11.0.W13` tags and did not find anything releavant: https://github.com/bonitasoft/bonita-engine/compare/7.11.0.W12...7.11.0.W13
Same for `bonita-userfilters`: https://github.com/bonitasoft/bonita-userfilters/compare/7.11.0.W12...7.11.0.W13

**Pull request merged**
