### PR TITLE
[dev] start building Bonita 7.12

### PR DESCRIPTION
**Pull request by tbouffard**
1st attempt to build the current developments for 7.12

### CODE REVIEW

**Comment by tbouffard** [comment]
7.12.0.W40 build error
```
An exception occurred applying plugin request [id: 'me.champeau.gradle.jmh', version: '0.5.0']

> Failed to apply plugin [id 'me.champeau.gradle.jmh']

   > This version of the JMH Gradle plugin requires Gradle 5.5+.
   Please upgrade Gradle or use an older version of the plugin.
```

Should be fixed by https://github.com/bonitasoft/bonita-engine/commit/16acbecdfe1d5f42d2c6f495c96fa1b5ffbb0f85

**Comment by educhastenier** [comment]
retest this please

**Comment by educhastenier** [comment]
@tbouffard Gradle has been upgraded (https://github.com/bonitasoft/bonita-engine/commit/16acbecdfe1d5f42d2c6f495c96fa1b5ffbb0f85).
Can you relaunch Travis job?

**Comment by tbouffard** [comment]
@educhastenier I could but the new build would fail as well. This project only build git tag for now (for branch build, see #41) and the fix is currently only available in the bonita-engine `dev` branch.
An alternative could be to build an old git tag, but we can also wait for the next weekly tag that is supposed to contain the fix.

**Comment by tbouffard** [comment]
Build issue with b66e808
The alfresco connector version retrieved from the Studio pom.xml is empty.

In Bonita 7.12, the connector list bundle within the Studio has been updated and some connectors are now directly available on Maven Central
- [ ] check if the alfresco connector is still needed
- [ ] detect already available connectors on Maven Central and don't build them anymore.

**Comment by rbioteau** [comment]
Update to the last weekly tag + update to studio build dependencies [here](https://github.com/Bonitasoft-Community/Build-Bonita/pull/70)

**Pull request closed without merging**
